spring:
  application:
    name: experimental_service
  # JPA datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/experimentalservice_db
    username: portal
    password: troP4444
    driver-class-name: org.postgresql.Driver
    #jndi-name: dataSource
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: experimentalservice
        dialect: org.hibernate.dialect.PostgreSQLDialect  # !пришлось указать диалект
    show-sql: true
  # JDBC datasource
  data-collector-db:
    #data.jdbc.repositories.enabled: false
    data.jdbc.database: jdbc:postgresql://localhost:5432/datacollectorservice_db
    data.jdbc.username: portal
    data.jdbc.password: troP4444
    driver-class-name: org.postgresql.Driver
  data.jdbc.repositories.enabled: false
  #data.jdbc.repositories.enabled: true
  #data.jdbc.database: jdbc:postgresql://localhost:5432/datacollectorservice_db
  #data.jdbc.username: portal
  #data.jdbc.password: troP4444
  #####
  liquibase:
    enabled: true #!!!!!!! ошибка
    default-schema: experimentalservice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    
server:
  port: 33333

