spring:
  application:
    name: experimental_service
  datasource:
    url: jdbc:postgresql://localhost:5432/experimentalservice_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: experimentalservice
    show-sql: true
  liquibase:
    enabled: true
    default-schema: experimentalservice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    
server:
  port: 33333
